name: Rakit Exambro & Kirim Telegram

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Tarik Kodingan
        uses: actions/checkout@v3

      - name: Siapkan Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Beri Izin Eksekusi Gradle
        run: chmod +x gradlew

      - name: Hapus Settingan Java Windows
        run: sed -i '/org.gradle.java.home/d' gradle.properties || true

      - name: Rakit APK
        run: ./gradlew assembleDebug

      - name: Kirim ke Telegram
        run: |
          ANGKA_ACAK=$RANDOM
          NAMA_FILE="Exambro_Paramarta_$ANGKA_ACAK.apk"
          
          cp app/build/outputs/apk/debug/app-debug.apk $NAMA_FILE
          
          for ID in 6071587883 7520038758; do
            curl -F document=@"$NAMA_FILE" \
                 -F caption=$'🚀 *EXAMBRO PARAMARTA: CLOUD BUILD SUCCESS!* 🚀\n\nMesin: GitHub Actions\nStatus: Siap diuji! Silakan unduh.' \
                 "https://api.telegram.org/bot8825507034:AAE6-v3lKkBrfjJJ3lTR7dtaXIwfr1GzHJ8/sendDocument?chat_id=$ID"
          done